version: "3.5"
services:
  dev:
    build:
      context: .
    container_name: arterys-inference-sdk-server
    working_dir: /opt
    volumes:
      - ./:/opt
    ports:
      - 8900:8000
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - S3_AUDIT_BUCKET_NAME=arterys-inference-sdk-audit-dev-account
